### ISSUE TITLE
Border Issue!

### ISSUE THREAD

**Issue by pr0fite** [Rehok/rLST#1]
Hey i just saw an Issue with the Item Quality Border and the Backround, the Black Backround is a little too Long on the Right side of the Toasts.
![lstoasts](https://user-images.githubusercontent.com/31422144/29795214-920cecfe-8c4b-11e7-97d6-95dceff8b73a.png)

**Comment by Rhkqt** [comment]
Will update it tonight, Trying to eyeball it is hard! :D.

**Comment by Rhkqt** [comment]
Will actually need to wait until the weekend as i currently don't hjave time to fix it.

**Comment by Rhkqt** [comment]
Commit 7ff06e1 fixes this.
