### ISSUE TITLE
Typo on Line 38 still not fixed

### ISSUE THREAD

**Issue by Crelam** [Rehok/rLST#4]
Downloaded and installed v1.0.7-release.  Issue still persists, receiving following error:

ls_Toasts_Rehok.lua line 38: attempt to index field 'iconHL' (a nil value)

I do not use ElvUI, is that where this field is defined?  Regardless, capitalizing the I in icon, squashes the bug.

**Comment by Rhkqt** [comment]
This has no link to ElvUI, I just forgot to cap the i, should be fixed now
