### ISSUE TITLE
201x Couldn't open rLST\

### ISSUE THREAD

**Issue by Jbleedge** [Rehok/rLST#5]
Buggrabber keep pointing to this: 

201x Couldn't open rLST\

**Comment by Rhkqt** [comment]
Install https://github.com/Nevcairiel/FilterLuaInterfaceWarnings as its not an issue i can fix, Its new errors that blizzard starting showing.

**Comment by Jbleedge** [comment]
Hello, just one thing: Where do I put those files? (FilterLuaInterfaceWarnings)?

Thanks

**Comment by Rhkqt** [comment]
Extract it from the folder and put it in the addons like any other addon

**Comment by cybernami** [comment]
Just to let you know... it seems like excessive use of empty newlines at the end in toc creates this error msg?... TellMeWhen seem to fix it by removing them according to he's changelog https://github.com/ascott18/TellMeWhen/commit/c752ac3cb3d0057fc670df0043bfe60b677045d1

I noticed your toc file has 2 newlines like the one he removed
Maybe it helps?

**Comment by Jbleedge** [comment]
I've put FilterLuaInterfaceWarnings into Interface/Addons but I still have those errors

**Comment by cybernami** [comment]
I have just verified it after getting home from work

Remove empty new lines at end of file seems to remove the error
